name: Build Binaries

on:
  push:
    tags:
      - 'build-binaries'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: mac

    runs-on: ${{ matrix.os }}

    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v4

      - name: 🔨 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.14.0'

      - name: 👷 Install dependencies
        run: |
          npm ci
          npm install https://github.com/greenheartgames/greenworks.git#v0.22.0

      - name: ⬆️ Upload electron artifact
        uses: actions/upload-artifact@v4
        with:
          name: electron-${{ matrix.platform }}
          path: node_modules/electron/dist/

      - name: ⬆️ Upload greenworks artifact
        uses: actions/upload-artifact@v4
        with:
          name: greenworks-${{ matrix.platform }}
          path: node_modules/greenworks/build/Release/
